<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8YKdJoy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8YKdJoy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8YKdJoy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8YKdJoy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8YKdJoy\App_KernelDevDebugContainer([
    'container.build_hash' => '8YKdJoy',
    'container.build_id' => '0b9479c9',
    'container.build_time' => 1626043880,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8YKdJoy');
